import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import "./globals.css";
import localFont from 'next/font/local'

const helveticaNowDisplay = localFont({
  src: [
    {
      path: './fonts/HelveticaNowDisplay-Regular.woff2',
      weight: '400',
      style: 'normal',
    },

    {
      path: './fonts/HelveticaNowDisplay-Bold.woff2',
      weight: '700',
      style: 'normal',
    },

  ],
})

export const metadata = {
  title: "Lorem Ipsum",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.svg",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={helveticaNowDisplay.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
